In [2]:
import numpy as np

In [15]:
a = [0,1,2,3,4,5,6,7,8]

In [16]:
def calculate(list):
    b = np.array(list)
    matrix = b.reshape(3, 3)
    return matrix

In [17]:
print(calculate(l))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
